### ISSUE TITLE
Archetypes have the same custom tag as the base class, causing references to break if both are added.

### ISSUE THREAD

**Issue by Tarbarian** [baileymh/pf1e-archetypes#6]
As the archetypes have no save bonuses, class feature associations, etc. and start at level 0, I would assume that they are meant to just be added on top of the existing class to mark that actor as having said archetype. However, if you do that since the archetypes have the same custom tag, references like `@classes.___.level` break as there are two classes with the same tag. 
Not sure how you want to handle that, but the easiest would probably be to change the custom tags on the existing archetypes, or at least warn people of this.

**Comment by baileymh** [comment]
Will change the names to something separate.
