### ISSUE TITLE
Manifest URL on foundryvtt.com is broken

### ISSUE THREAD

**Issue by DrMcCoy** [baileymh/pf1e-archetypes#9]
Similar issue as in https://github.com/baileymh/statblock-library/issues/8.

The Manifest URL should probably be
`https://github.com/baileymh/pf1e-archetypes/releases/download/0.2.3/module.json`
instead of
`https://github.com/baileymh/pf1e-archetypes/releases/latest/module.json`

**Comment by baileymh** [comment]
Fixed
